version: "3"

services:
  mermithid:
    build: .
    command: "/bin/bash"
    volumes:
      # share a subdirectory from the host to /host in the docker (can be edited)
      - ~/mermithid_share:/host
      - ~/mermithid_FDG2/mermithid:/host-mermithid
      - ~:/home_directory