FROM project8/p8compute_dependencies:v0.2.0 as mermithid_common

ENV MERMITHID_TAG=v1.0.5
ENV MERMITHID_BUILD_PREFIX=/usr/local/p8/locust/$MERMITHID_TAG

RUN mkdir -p $MERMITHID_BUILD_PREFIX &&\
    cd $MERMITHID_BUILD_PREFIX &&\
    echo "source ${COMMON_BUILD_PREFIX}/setup.sh" > setup.sh &&\
    echo "export MERMITHID_TAG=${MERMITHID_TAG}" >> setup.sh &&\
    echo "export MERMITHID_BUILD_PREFIX=${MERMITHID_BUILD_PREFIX}" >> setup.sh &&\
    echo 'ln -sf $MERMITHID_BUILD_PREFIX $MERMITHID_BUILD_PREFIX/../current' >> setup.sh &&\
    echo 'export PATH=$MERMITHID_BUILD_PREFIX/bin:$PATH' >> setup.sh &&\
    echo 'export LD_LIBRARY_PATH=$MERMITHID_BUILD_PREFIX/lib:$LD_LIBRARY_PATH' >> setup.sh &&\
    /bin/true

########################
FROM mermithid_common as mermithid_done

# repeat the cmake command to get the change of install prefix to set correctly (a package_builder known issue)
RUN source $MERMITHID_BUILD_PREFIX/setup.sh &&\
    mkdir /tmp_install &&\
    cd /tmp_install &&\
    git clone https://github.com/project8/mermithid &&\
    cd mermithid &&\
    git checkout develop &&\
    git submodule update --init --recursive &&\
    mkdir build &&\
    cd build &&\
    cmake -D CMAKE_INSTALL_PREFIX:PATH=$MERMITHID_BUILD_PREFIX .. &&\
    cmake -D CMAKE_INSTALL_PREFIX:PATH=$MERMITHID_BUILD_PREFIX .. &&\
    make -j3 install &&\
    /bin/true

########################
FROM mermithid_common

COPY --from=mermithid_done $MERMITHID_BUILD_PREFIX $MERMITHID_BUILD_PREFIX

RUN source $MERMITHID_BUILD_PREFIX/setup.sh &&\
    cd $MERMITHID_BUILD_PREFIX &&\
    pip3 install . --process-dependency-links
    